### ISSUE TITLE
Illegal format option

### ISSUE THREAD

**Issue by smolnar** [yalesov/vim-ember-script#1]
Hi,

I bundled you plugin and I get the following error:

```
E539: Illegal character <j>: formatoptions+=croql
```

It's possible that I have old version of vim (VIM - Vi IMproved 7.3 (2010 Aug 15, compiled May  4 2012 04:21:49), since I read the `j` option is only available in new patches of 7.3. Is it possible to resolve this issue and make your plugin compatible with older version?

Thanks

**Comment by yalesov** [comment]
@smolnar a detection for vim version (`<7.3`) added
